# Generated by Django 5.0.4 on 2024-04-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_large',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
    ]
