# Generated by Django 5.0.4 on 2024-04-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('ram', 'ram'), ('graphics', 'graphics'), ('storage', 'storage'), ('color', 'color'), ('size', 'size')], max_length=100),
        ),
    ]
